<?php

namespace Repository;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-27 at 11:27:37.
 */
class QueryHelperTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var QueryHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new QueryHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Repository\QueryHelper::generateArgumentKeyFilter
     * @todo   Implement testGenerateArgumentKeyFilter().
     */
    public function testGenerateArgumentKeyFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Repository\QueryHelper::generateEntityKeyFilter
     * @todo   Implement testGenerateEntityKeyFilter().
     */
    public function testGenerateEntityKeyFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Repository\QueryHelper::generateQuery
     * @todo   Implement testGenerateQuery().
     */
    public function testGenerateQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Repository\QueryHelper::nullif
     * @todo   Implement testNullif().
     */
    public function testNullif() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Repository\QueryHelper::generateWhere
     * @todo   Implement testGenerateWhere().
     */
    public function testGenerateWhere() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Repository\QueryHelper::stringify
     * @todo   Implement testStringify().
     */
    public function testStringify() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
