<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-12 at 09:10:38.
 */
class EncryptPasswordTest extends \PHPUnit_Framework_TestCase
{

    protected function setUp()
    {
    }

    protected function tearDown()
    {
    }
    /**
     * @covers Services\EncryptPasswordService::encode
     * @todo   Implement testFindByEntityId().
     */
    // public function testDecodeOfEncodeIsTheSame()
    // {

    //     $password_in_plain_text = 'secret';
    //     $converter = new \Services\EncryptPasswordService();
    //     $encoded = $converter->encode($password_in_plain_text);
    //     $decoded = $converter->decode($encoded);    

    //     $this->assertEquals($password_in_plain_text, $decoded);
                
    // }

}
