<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:sead" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:sead">
<types>
<xsd:schema targetNamespace="urn:sead"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="doUploadRequest">
  <part name="user" type="xsd:string" />
  <part name="password" type="xsd:string" />
  <part name="file" type="xsd:string" />
  <part name="datatypes" type="xsd:string" /></message>
<message name="doUploadResponse">
  <part name="return" type="xsd:string" /></message>
<portType name="uploadPortType">
  <operation name="doUpload">
    <documentation>Upload a file attached to the caller.</documentation>
    <input message="tns:doUploadRequest"/>
    <output message="tns:doUploadResponse"/>
  </operation>
</portType>
<binding name="uploadBinding" type="tns:uploadPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="doUpload">
    <soap:operation soapAction="urn:sead#doUpload" style="rpc"/>
    <input><soap:body use="literal" namespace="urn:sead"/></input>
    <output><soap:body use="literal" namespace="urn:sead"/></output>
  </operation>
</binding>
<service name="upload">
  <port name="uploadPort" binding="tns:uploadBinding">
    <soap:address location="http://127.0.0.1/SEAD_ClearingHouse/public/api/Application/Soap/doUpload.php"/>
  </port>
</service>
</definitions>