-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_analysis_entities');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_dating_uncertainty');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_feature_types');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_alt_refs');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_site_references');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_group_description_type_sampling_contexts');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_contacts');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_method_groups');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_locations');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_group_sampling_contexts');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_group_description_types');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_relative_dates');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_relative_ages');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_units');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_description_types');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_features');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_dataset_masters');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_biblio');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_dataset_contacts');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_datasets');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_methods');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_location_types');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_groups');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_physical_samples');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_data_type_groups');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_types');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_group_dimensions');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_site_locations');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_dimensions');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_contact_types');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sample_group_descriptions');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_physical_sample_features');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_dataset_submissions');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_alt_ref_types');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_ceramics');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_sites');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_dimensions');
-- SELECT * FROM   clearing_house.fn_copy_extracted_values_to_entity_table(1, 'tbl_ceramics_lookup');

-- PK saknas i XML/EXCEL för tbl_ceramics_lookup
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183096;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183102;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183108;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183114;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183120;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183126;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183132;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183138;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183144;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183150;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183156;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183162;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183168;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183174;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183180;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183186;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183192;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183198;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183204;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183210;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183216;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183222;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183228;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183234;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183240;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183246;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183252;
UPDATE clearing_house.tbl_clearinghouse_submission_xml_content_values SET value = local_db_id WHERE value is NULL AND value_id = 1183258;

    