

-- DROP SCHEMA IF EXISTS sead_lookup CASCADE;

CREATE SCHEMA IF NOT EXISTS sead_lookup AUTHORIZATION sead_master;

GRANT USAGE ON SCHEMA sead_lookup TO public;

GRANT SELECT ON ALL TABLES IN SCHEMA sead_lookup to public;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA sead_lookup TO public;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON ALL TABLES TO public;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON ALL SEQUENCES TO public;

ALTER TABLE tbl_locations
    SET SCHEMA sead_lookup;


